version: '2'

services:
  webserver:
    #image: php:7.1-apache
    build: docker/webserver
    ports:
      - '20080:80'
    volumes:
      - "$PWD:/var/www/html"
      #- "$PWD/docker/webserver/vhosts:/etc/apache2/sites-enabled"
      #- "$PWD/docker/webserver/php:/usr/local/etc/php"
    links:
      - mysql

  mysql:
    image: mysql:5.7.10
    environment:
      MYSQL_ROOT_PASSWORD: 'secret'
    ports:
      - '23306:3306'
    volumes:
      - "$PWD/docker/mysql:/etc/mysql"
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
    driver: local
